/**
 * Prebuilt RAG (Retrieval-Augmented Generation) System for VowelDocs
 *
 * This module provides a privacy-first, browser-based RAG system using Haven
 * with pre-built embeddings. Instead of chunking and embedding documents at
 * runtime, it loads a pre-computed YAML artifact generated by the build script.
 *
 * Benefits:
 * - Instant initialization (no client-side embedding computation)
 * - Consistent chunking and embeddings (same model, same processing)
 * - Smaller bundle (no need to bundle all MDX files)
 * - Better performance (no WASM/WebGPU model loading for embedding generation)
 *
 * @module prebuilt-rag
 */

import * as yaml from 'js-yaml';
import { VectorDB } from 'haven';

// =============================================================================
// TYPES & INTERFACES
// =============================================================================

/**
 * Represents a pre-built document chunk with embedding and metadata
 */
export interface PrebuiltChunk {
  /** Unique identifier for the chunk */
  id: string;
  /** The text content of the chunk (with context prefix) */
  text: string;
  /** 384-dimensional embedding vector (new format uses 'vector', old used 'embedding') */
  vector?: number[];
  /** 384-dimensional embedding vector @deprecated Use 'vector' instead */
  embedding?: number[];
  /** Metadata about the chunk */
  metadata: {
    /** Document title from frontmatter */
    title: string;
    /** Full file path */
    path: string;
    /** URL-friendly path */
    urlPath: string;
    /** Category/folder name */
    category: string;
    /** Chunk index within the document */
    chunkIndex: number;
    /** Total chunks for this document */
    totalChunks: number;
    /** Estimated position in document (0-1) */
    position: number;
  };
}

/**
 * Prebuilt index structure from build-rag.py
 */
export interface PrebuiltIndex {
  version: string;
  model: string;
  dimensions: number;
  metric: string;
  generated_at: string;
  chunk_count: number;
  chunks: PrebuiltChunk[];
}

/**
 * Search result from the vector database
 */
export interface SearchResult {
  /** The document chunk text */
  text: string;
  /** Similarity score (0-1, higher is better) */
  score: number;
  /** Document metadata */
  metadata: PrebuiltChunk['metadata'];
}

/**
 * Progress callback for initialization
 */
export interface InitializationProgress {
  /** Current stage of initialization */
  stage: 'fetching' | 'loading' | 'indexing' | 'complete' | 'error';
  /** Progress percentage (0-100) */
  progress: number;
  /** Total number of chunks to process */
  total: number;
  /** Number of chunks processed so far */
  processed: number;
  /** Human-readable status message */
  message: string;
}

/**
 * RAG initialization and search interface
 */
export interface PrebuiltRAG {
  /** Initialize the RAG system (loads prebuilt index) */
  initialize(progressCallback?: (progress: InitializationProgress) => void): Promise<void>;
  /** Search for relevant documentation */
  search(query: string, k?: number): Promise<SearchResult[]>;
  /** Check if the database is ready */
  isReady(): boolean;
  /** Get total number of indexed chunks */
  getIndexSize(): Promise<number>;
  /** Force reload the prebuilt index */
  reload(progressCallback?: (progress: InitializationProgress) => void): Promise<void>;
  /** Clear the vector database without reinitializing. Call reload() to reindex. */
  clearIndex(): Promise<void>;
  /** Get the prebuilt index (for document listing) */
  getPrebuiltIndex(): PrebuiltIndex | null;
  /** Get all unique documents from the prebuilt index */
  getDocuments(): Array<{ title: string; path: string; category: string; chunkCount: number; urlPath: string }>;
}

/**
 * Current initialization state
 */
export interface InitializationState {
  /** Whether initialization is in progress */
  isInitializing: boolean;
  /** Current progress (0-100) */
  progress: number;
  /** Current stage */
  stage: InitializationProgress['stage'];
  /** Total chunks */
  totalChunks: number;
  /** Processed chunks */
  processedChunks: number;
  /** Error message if failed */
  error: string | null;
  /** Human-readable status message */
  message: string;
}

// =============================================================================
// STATE
// =============================================================================

/** Global initialization state for UI feedback */
const initializationState: InitializationState = {
  isInitializing: false,
  progress: 0,
  stage: 'fetching',
  totalChunks: 0,
  processedChunks: 0,
  error: null,
  message: 'Not initialized',
};

/**
 * Get the current initialization state
 * @returns Current state (useful for UI progress indicators)
 */
function getInitializationState(): InitializationState {
  return { ...initializationState };
}

/**
 * Subscribe to initialization state changes
 * @param callback - Called whenever state changes
 * @returns Unsubscribe function
 */
function subscribeToInitializationState(callback: (state: InitializationState) => void): () => void {
  const wrappedCallback = () => callback(getInitializationState());
  stateSubscribers.add(wrappedCallback);
  return () => stateSubscribers.delete(wrappedCallback);
}

/** Set of state subscribers */
const stateSubscribers = new Set<() => void>();

/**
 * Notify all subscribers of state change
 */
function notifyStateChange(): void {
  for (const subscriber of stateSubscribers) {
    try {
      subscriber();
    } catch (error) {
      console.warn('[prebuilt-rag] State subscriber error:', error);
    }
  }
}

/**
 * Update initialization state and notify subscribers
 */
function updateState(updates: Partial<InitializationState>): void {
  Object.assign(initializationState, updates);
  notifyStateChange();
}

// =============================================================================
// CONFIGURATION
// =============================================================================

/** VectorDB configuration constants */
const DB_CONFIG = {
  /** IndexedDB database name */
  DB_NAME: 'voweldocs-prebuilt-rag-v1',
  /** Vector dimensions (matches Xenova/all-MiniLM-L6-v2) */
  DIMENSIONS: 384,
  /** Distance metric for similarity search */
  METRIC: 'cosine' as const,
  /** Embedding model (for query embedding) */
  EMBEDDING_MODEL: 'Xenova/all-MiniLM-L6-v2',
  /** Device for query embedding computation */
  DEVICE: 'wasm' as const,
  /** Default chunks to retrieve per search */
  DEFAULT_K: 5,
  /** Storage key for tracking loaded index */
  LOADED_KEY: 'voweldocs-prebuilt-rag-loaded',
  /** Prebuilt index URL */
  INDEX_URL: '/rag-index.yml',
};

// =============================================================================
// HAVEN VECTOR DATABASE
// =============================================================================

/** Haven VectorDB instance type */
type HavenVectorDB = InstanceType<typeof VectorDB>;

/** Global VectorDB instance */
let vectorDB: HavenVectorDB | null = null;

/** Prebuilt index cache */
let prebuiltIndex: PrebuiltIndex | null = null;

/** Initialization state */
let isInitialized = false;
let initializationPromise: Promise<void> | null = null;

/**
 * Get or create the VectorDB instance.
 * Uses lazy initialization with singleton pattern.
 *
 * Unlike the original local-rag.ts, this version:
 * - Does NOT auto-load and embed all MDX files
 * - Loads pre-computed embeddings from JSON artifact
 * - Only needs embedding model for query embedding
 */
async function getVectorDB(): Promise<HavenVectorDB> {
  if (vectorDB) return vectorDB;

  if (typeof window === 'undefined') {
    throw new Error('Prebuilt RAG can only be used in browser environment');
  }

  const hasWebGPU = typeof navigator !== 'undefined' && 'gpu' in navigator;

  vectorDB = new VectorDB({
    storage: { dbName: DB_CONFIG.DB_NAME },
    index: {
      indexType: 'kdtree',
      dimensions: DB_CONFIG.DIMENSIONS,
      metric: DB_CONFIG.METRIC,
    },
    embedding: {
      model: DB_CONFIG.EMBEDDING_MODEL,
      device: hasWebGPU ? 'webgpu' : DB_CONFIG.DEVICE,
      cache: true,
    },
  });

  await vectorDB.initialize();
  return vectorDB;
}

// =============================================================================
// PREBUILT INDEX LOADING
// =============================================================================

/**
 * Fetch the prebuilt index from the server.
 * This is the YAML artifact generated by build-rag.py.
 */
async function fetchPrebuiltIndex(): Promise<PrebuiltIndex> {
  console.log('[prebuilt-rag] Fetching prebuilt index...');

  const response = await fetch(DB_CONFIG.INDEX_URL);

  if (!response.ok) {
    throw new Error(`Failed to fetch prebuilt index: ${response.status} ${response.statusText}`);
  }

  const yamlText = await response.text();
  console.log(`[prebuilt-rag] Fetched ${yamlText.length} bytes`);

  if (!yamlText || yamlText.trim().length === 0) {
    throw new Error('Prebuilt index file is empty');
  }

  // Check for fetch of HTML error page instead of YAML
  if (yamlText.trim().startsWith('<!DOCTYPE') || yamlText.trim().startsWith('<html')) {
    throw new Error('Received HTML instead of YAML - prebuilt index file not found at ' + DB_CONFIG.INDEX_URL);
  }

  let index: unknown;
  try {
    index = yaml.load(yamlText);
  } catch (parseError) {
    console.error('[prebuilt-rag] YAML parse error:', parseError);
    throw new Error(`Failed to parse prebuilt index YAML: ${parseError instanceof Error ? parseError.message : String(parseError)}`);
  }

  if (!index || typeof index !== 'object') {
    console.error('[prebuilt-rag] Parsed index is not an object:', index);
    throw new Error('Failed to parse prebuilt index: invalid YAML structure (got ' + typeof index + ')');
  }

  const prebuiltIndex = index as PrebuiltIndex;

  if (typeof prebuiltIndex.chunk_count !== 'number' || !Array.isArray(prebuiltIndex.chunks)) {
    console.error('[prebuilt-rag] Index missing required fields:', { chunk_count: prebuiltIndex.chunk_count, chunks: typeof prebuiltIndex.chunks });
    throw new Error(`Prebuilt index missing required fields: chunk_count=${prebuiltIndex.chunk_count}, chunks=${Array.isArray(prebuiltIndex.chunks)}`);
  }

  console.log(`[prebuilt-rag] ✓ Loaded prebuilt index: ${prebuiltIndex.chunk_count} chunks, model: ${prebuiltIndex.model}`);

  return prebuiltIndex;
}

/**
 * Check if the prebuilt index has already been loaded into IndexedDB.
 */
function isAlreadyLoaded(): boolean {
  try {
    const loaded = localStorage.getItem(DB_CONFIG.LOADED_KEY);
    if (!loaded) return false;

    const { version, timestamp } = JSON.parse(loaded);
    // Check version match and index is less than 30 days old
    const isRecent = Date.now() - timestamp < 30 * 24 * 60 * 60 * 1000;
    return version === DB_CONFIG.DB_NAME && isRecent;
  } catch {
    return false;
  }
}

/**
 * Mark the prebuilt index as loaded in localStorage.
 */
function markAsLoaded(count: number): void {
  try {
    localStorage.setItem(
      DB_CONFIG.LOADED_KEY,
      JSON.stringify({
        version: DB_CONFIG.DB_NAME,
        timestamp: Date.now(),
        count: count,
      })
    );
  } catch (error) {
    console.warn('[prebuilt-rag] Failed to mark as loaded:', error);
  }
}

/**
 * Load the prebuilt index into the vector database.
 * Uses batch insertion for performance with progress tracking.
 */
async function loadPrebuiltIndex(
  db: HavenVectorDB,
  index: PrebuiltIndex,
  progressCallback?: (progress: InitializationProgress) => void
): Promise<void> {
  console.log('[prebuilt-rag] Loading prebuilt index into VectorDB...');
  const startTime = performance.now();

  if (index.chunks.length === 0) {
    console.warn('[prebuilt-rag] No chunks in prebuilt index');
    updateState({ stage: 'complete', progress: 100, isInitializing: false, message: 'No chunks to load' });
    progressCallback?.({ stage: 'complete', progress: 100, total: 0, processed: 0, message: 'No chunks to load' });
    return;
  }

  updateState({ totalChunks: index.chunks.length, processedChunks: 0, stage: 'indexing', message: `Loading ${index.chunks.length} chunks...` });

  // Prepare documents for batch insert
  // Note: We pass the pre-computed vectors directly to Haven
  // Haven expects 'vector' field (not 'embedding' which was used in old format)
  const documents = index.chunks.map(chunk => {
    // Support both new format (vector) and old format (embedding)
    const vectorData = chunk.vector || chunk.embedding;
    if (!vectorData) {
      throw new Error(`Chunk ${chunk.id} has neither 'vector' nor 'embedding' field`);
    }
    return {
      id: chunk.id,
      text: chunk.text, // Keep for embedding generation
      vector: new Float32Array(vectorData),
      metadata: {
        ...chunk.metadata,
        text: chunk.text, // Store text in metadata so it's returned in search results
      },
    };
  });

  // Batch insert for better performance
  const BATCH_SIZE = 100;
  const totalBatches = Math.ceil(documents.length / BATCH_SIZE);

  for (let i = 0; i < documents.length; i += BATCH_SIZE) {
    const batch = documents.slice(i, i + BATCH_SIZE);
    const batchNum = Math.floor(i / BATCH_SIZE) + 1;

    await db.insertBatch(batch);

    const processed = Math.min(i + batch.length, documents.length);
    const progress = Math.round((processed / documents.length) * 100);

    updateState({ processedChunks: processed, progress, message: `Loading batch ${batchNum}/${totalBatches}...` });

    const message = `Loading batch ${batchNum}/${totalBatches} (${batch.length} chunks)`;
    console.log(`[prebuilt-rag] ${message}`);

    progressCallback?.({
      stage: 'indexing',
      progress,
      total: documents.length,
      processed,
      message,
    });
  }

  const duration = Math.round(performance.now() - startTime);
  console.log(`[prebuilt-rag] ✓ Index loaded: ${documents.length} chunks in ${duration}ms`);

  updateState({ stage: 'complete', progress: 100, isInitializing: false, message: `Loaded ${documents.length} chunks` });
  progressCallback?.({
    stage: 'complete',
    progress: 100,
    total: documents.length,
    processed: documents.length,
    message: `Loaded ${documents.length} chunks in ${duration}ms`,
  });

  markAsLoaded(documents.length);
}

// =============================================================================
// PUBLIC API
// =============================================================================

/**
 * Initialize the Prebuilt RAG system.
 * This is called automatically on first use and will:
 * 1. Initialize the VectorDB (with embedding model for queries)
 * 2. Load the prebuilt index (if not already loaded)
 *
 * @param progressCallback - Optional callback for progress updates
 * @returns Promise that resolves when initialization is complete
 */
async function initialize(progressCallback?: (progress: InitializationProgress) => void): Promise<void> {
  if (isInitialized) {
    progressCallback?.({
      stage: 'complete',
      progress: 100,
      total: prebuiltIndex?.chunk_count || 0,
      processed: prebuiltIndex?.chunk_count || 0,
      message: 'Already initialized',
    });
    return;
  }
  if (initializationPromise) {
    // If already initializing, just subscribe to state changes
    const unsubscribe = subscribeToInitializationState((state) => {
      if (state.stage !== 'complete' && state.stage !== 'error') {
        progressCallback?.({
          stage: state.stage,
          progress: state.progress,
          total: state.totalChunks,
          processed: state.processedChunks,
          message: state.error || `Loading... (${state.progress}%)`,
        });
      }
    });
    // Unsubscribe when initialization completes
    await initializationPromise;
    unsubscribe();
    return initializationPromise;
  }

  updateState({ isInitializing: true, stage: 'fetching', progress: 0, error: null, message: 'Starting initialization...' });
  progressCallback?.({
    stage: 'fetching',
    progress: 0,
    total: 0,
    processed: 0,
    message: 'Starting initialization...',
  });

  initializationPromise = (async () => {
    try {
      console.log('[prebuilt-rag] Initializing Prebuilt RAG system...');

      const loadingMsg = 'Initializing VectorDB...';
      updateState({ stage: 'loading', progress: 10, message: loadingMsg });
      progressCallback?.({
        stage: 'loading',
        progress: 10,
        total: 0,
        processed: 0,
        message: loadingMsg,
      });

      const db = await getVectorDB();

      const checkingMsg = 'VectorDB initialized, checking cache...';
      updateState({ stage: 'loading', progress: 20, message: checkingMsg });
      progressCallback?.({
        stage: 'loading',
        progress: 20,
        total: 0,
        processed: 0,
        message: checkingMsg,
      });

      // Check if we need to load the prebuilt index
      if (!isAlreadyLoaded() || prebuiltIndex === null) {
        console.log('[prebuilt-rag] Loading prebuilt index...');

        const fetchingMsg = 'Fetching prebuilt index...';
        updateState({ stage: 'fetching', progress: 30, message: fetchingMsg });
        progressCallback?.({
          stage: 'fetching',
          progress: 30,
          total: 0,
          processed: 0,
          message: fetchingMsg,
        });

        // Fetch the prebuilt index
        const index = await fetchPrebuiltIndex();
        prebuiltIndex = index;

        const fetchedMsg = `Fetched ${index.chunk_count} chunks, clearing existing data...`;
        updateState({ totalChunks: index.chunk_count, stage: 'loading', progress: 50, message: fetchedMsg });
        progressCallback?.({
          stage: 'loading',
          progress: 50,
          total: index.chunk_count,
          processed: 0,
          message: fetchedMsg,
        });

        // Clear any existing data (in case of version mismatch)
        await db.clear();

        // Load the prebuilt chunks with their embeddings
        await loadPrebuiltIndex(db, index, progressCallback);
      } else {
        const stats = JSON.parse(localStorage.getItem(DB_CONFIG.LOADED_KEY) || '{}');
        const count = stats.count || 'unknown';
        console.log(`[prebuilt-rag] Using existing index with ${count} chunks`);

        // Still need to load prebuiltIndex for getDocuments() to work
        if (prebuiltIndex === null) {
          prebuiltIndex = await fetchPrebuiltIndex();
        }

        const cachedMsg = `Using cached index (${count} chunks)`;
        updateState({ stage: 'complete', progress: 100, isInitializing: false, message: cachedMsg });
        progressCallback?.({
          stage: 'complete',
          progress: 100,
          total: typeof count === 'number' ? count : 0,
          processed: typeof count === 'number' ? count : 0,
          message: cachedMsg,
        });
      }

      isInitialized = true;
      console.log('[prebuilt-rag] Initialization complete');
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      console.error('[prebuilt-rag] Initialization failed:', error);
      updateState({ stage: 'error', isInitializing: false, error: errorMsg, message: `Error: ${errorMsg}` });
      progressCallback?.({
        stage: 'error',
        progress: 0,
        total: 0,
        processed: 0,
        message: `Error: ${errorMsg}`,
      });
      throw error;
    } finally {
      initializationPromise = null;
    }
  })();

  return initializationPromise;
}

/**
 * Search the documentation for relevant chunks.
 * Returns the top-k most semantically similar chunks to the query.
 *
 * @param query - The search query text
 * @param k - Number of results to return (default: 5)
 * @returns Array of search results with similarity scores
 */
async function search(query: string, k: number = DB_CONFIG.DEFAULT_K): Promise<SearchResult[]> {
  console.log('[prebuilt-rag] search() called with query:', query, 'k:', k);
  if (!isInitialized) {
    await initialize();
  }

  const db = await getVectorDB();
  console.log('[prebuilt-rag] calling db.search with text:', query);

  const results = await db.search({
    text: query,
    k,
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return results.map((result: any) => ({
    text: (result.metadata?.text ?? '') as string,
    score: result.score as number,
    metadata: result.metadata as PrebuiltChunk['metadata'],
  }));
}

/**
 * Check if the RAG system is initialized and ready.
 * @returns true if ready to accept searches
 */
function checkReady(): boolean {
  return isInitialized;
}

/**
 * Get the total number of indexed chunks.
 * @returns Promise resolving to the index size
 */
async function getIndexSize(): Promise<number> {
  if (!isInitialized) {
    await initialize();
  }
  const db = await getVectorDB();
  return await db.size();
}

/**
 * Force reload the prebuilt index.
 * Use this after updating documentation.
 */
async function reload(progressCallback?: (progress: InitializationProgress) => void): Promise<void> {
  console.log('[prebuilt-rag] Starting reload...');
  isInitialized = false;
  prebuiltIndex = null;
  updateState({ isInitializing: true, stage: 'fetching', progress: 0, error: null, message: 'Reloading index...' });

  try {
    localStorage.removeItem(DB_CONFIG.LOADED_KEY);
    const db = await getVectorDB();
    await db.clear();
    await initialize(progressCallback);
    console.log('[prebuilt-rag] Reload complete');
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    console.error('[prebuilt-rag] Reload failed:', error);
    updateState({ stage: 'error', isInitializing: false, error: errorMsg, message: `Error: ${errorMsg}` });
    throw error;
  }
}

/**
 * Clear the vector database without reinitializing.
 * Use this when you want to clear the index but not reload immediately.
 * Call reload() afterwards to reindex.
 */
async function clearIndex(): Promise<void> {
  console.log('[prebuilt-rag] Clearing index...');
  isInitialized = false;
  prebuiltIndex = null;
  
  try {
    localStorage.removeItem(DB_CONFIG.LOADED_KEY);
    const db = await getVectorDB();
    await db.clear();
    updateState({ isInitializing: false, stage: 'complete', progress: 0, error: null, message: 'Index cleared' });
    console.log('[prebuilt-rag] Index cleared');
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    console.error('[prebuilt-rag] Clear failed:', error);
    updateState({ stage: 'error', isInitializing: false, error: errorMsg, message: `Error: ${errorMsg}` });
    throw error;
  }
}

/**
 * Get the prebuilt index (for document listing).
 * Returns null if not loaded yet.
 */
function getPrebuiltIndex(): PrebuiltIndex | null {
  return prebuiltIndex;
}

/**
 * Get all unique documents from the prebuilt index.
 * Groups chunks by their document path to get unique documents.
 * @returns Array of documents with metadata
 */
function getDocuments(): Array<{ title: string; path: string; category: string; chunkCount: number; urlPath: string }> {
  if (!prebuiltIndex) {
    return [];
  }

  // Group chunks by document path
  const docMap = new Map<string, { title: string; path: string; category: string; urlPath: string; totalChunks: number }>();

  for (const chunk of prebuiltIndex.chunks) {
    const { path, title, category, urlPath, totalChunks } = chunk.metadata;

    if (!docMap.has(path)) {
      docMap.set(path, { title, path, category, urlPath, totalChunks });
    }
  }

  // Convert to array and sort by path
  const documents = Array.from(docMap.values()).map(doc => ({
    title: doc.title,
    path: doc.path,
    category: doc.category,
    chunkCount: doc.totalChunks,
    urlPath: doc.urlPath,
  }));

  return documents.sort((a, b) => a.path.localeCompare(b.path));
}

// =============================================================================
// EXPORT
// =============================================================================

/**
 * Prebuilt RAG instance for VowelDocs.
 * Provides semantic search over all documentation using pre-computed embeddings.
 */
export const prebuiltRAG: PrebuiltRAG = {
  initialize,
  search,
  isReady: checkReady,
  getIndexSize,
  reload,
  clearIndex,
  getPrebuiltIndex,
  getDocuments,
};

/**
 * Re-export reload for advanced usage
 */
export { reload, clearIndex, getInitializationState, subscribeToInitializationState, getPrebuiltIndex, getDocuments };

// Make available globally for debugging
if (typeof window !== 'undefined') {
  (window as any).__voweldocsPrebuiltRAG = {
    prebuiltRAG,
    reload,
    search: (q: string) => prebuiltRAG.search(q),
    size: () => prebuiltRAG.getIndexSize(),
    getDocuments: () => prebuiltRAG.getDocuments(),
    getState: getInitializationState,
  };
}
